"""empty message

Revision ID: 233e97226c4d
Revises: 779ee035a01f
Create Date: 2019-08-05 14:57:40.066498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e97226c4d'
down_revision = '779ee035a01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_finished')
    # ### end Alembic commands ###
